package com.makers.makersbnb.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

// tell Spring Boot this class is a controller
@RestController
public class StaticPageController {
    // tell Spring Boot this method handles the 'GET "/"' request
//    @GetMapping("/")
//    public String landingPage() {
//        return "Welcome to MakersBnB!";
//    }

    @GetMapping("/")
    public ModelAndView landingPage() {
        //When someone visits /, render the template called LandingPage:
        ModelAndView modelAndView = new ModelAndView("/LandingPage");
        // for now, imagine this value was generated by querying the database
        Integer nSpaces = 100;
        // this next line makes nSpaces available in the template
        modelAndView.addObject("nSpaces", nSpaces);
        // imagine these reviews were stored in a database
        String[] reviews = new String[]{"Awesome", "Nice", "Perfect"};
        modelAndView.addObject("reviews", reviews);
        Integer bookings = 123;
        modelAndView.addObject("bookings",bookings);
        return modelAndView;

//        return new ModelAndView("/LandingPage");
    }

    @GetMapping("/contactus")
    public ModelAndView contactPage() {
        ModelAndView modelAndView = new ModelAndView("/contactus");
        String email = "makersbnb@gmail.com";
        modelAndView.addObject("email", email);
        return modelAndView;
    }
//    @GetMapping("/team")
//    public ModelAndView teamPage(){
//        ModelAndView modelAndView = new ModelAndView("/team");
//        String team = "Toby, Katerina, Sandy";
//        modelAndView.addObject("team",team);
//        return modelAndView;
//    }
}

