package com.makers.makersbnb.controller;

import com.makers.makersbnb.model.Space;
import com.makers.makersbnb.repository.SpaceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

// tell Spring Boot this class is a controller
@RestController
public class StaticPageController {
    // tell Spring Boot this method handles the 'GET "/"' request
//    @GetMapping("/")
//    public String landingPage() {
//        return "Welcome to MakersBnB!";
//    }

//declares a variable called spaceRepository,
// of type SpaceRepository (the interface I built earlier):
    //autowired tells springboot to create this automatically , and create a
    //working version when automatically built when the app starts
    @Autowired
    SpaceRepository spaceRepository;

    @GetMapping("/")
    public ModelAndView landingPage() {
        //creates a new object and tells it what page to render:
        ModelAndView modelAndView = new ModelAndView("/LandingPage");
        //calling count which comes from using CrudRepository which then runs a
        // //sql SELEct count query
        Integer nSpaces = (int) spaceRepository.count();
        //this makes this data accessible in my HTML files:
        modelAndView.addObject("nSpaces", nSpaces);
        String[] reviews = new String[]{"Awesome", "Nice", "Perfect"};
        modelAndView.addObject("reviews", reviews);
        Integer bookings = 123;
        modelAndView.addObject("bookings", bookings);
        //Sends the whole bundle (template & data) back to springboot,
        // which renders the page and sends it to the browser:
        return modelAndView;
    }


    @GetMapping("/spaces")
    public ModelAndView spacePage(){
        //render a template file called spaces:
        ModelAndView modelAndView = new ModelAndView("/spaces");
        //another method from CrudRepository,
        // it fetches every row from my spaces table
        // and returns them as a list of space objects
        Iterable<Space> spaces =spaceRepository.findAll();
        modelAndView.addObject("spaces", spaces);
        Integer nSpaces = (int) spaceRepository.count();
        modelAndView.addObject("nSpaces", nSpaces);
        return modelAndView;
    }

    @GetMapping("/contactus")
    public ModelAndView contactPage() {
        ModelAndView modelAndView = new ModelAndView("/contactus");
        String email = "makersbnb@gmail.com";
        modelAndView.addObject("email", email);
        return modelAndView;
    }

//old code:
//    @GetMapping("/")
//    public ModelAndView landingPage() {
//        //When someone visits /, render the template called LandingPage:
//        ModelAndView modelAndView = new ModelAndView("/LandingPage");
//        // for now, imagine this value was generated by querying the database
//        Integer nSpaces = 100;
//        // this next line makes nSpaces available in the template
//        modelAndView.addObject("nSpaces", nSpaces);
//        // imagine these reviews were stored in a database
//        String[] reviews = new String[]{"Awesome", "Nice", "Perfect"};
//        modelAndView.addObject("reviews", reviews);
//        Integer bookings = 123;
//        modelAndView.addObject("bookings",bookings);
//        return modelAndView;

//        return new ModelAndView("/LandingPage");
    // }
//    @GetMapping("/team")
//    public ModelAndView teamPage(){
//        ModelAndView modelAndView = new ModelAndView("/team");
//        String team = "Toby, Katerina, Sandy";
//        modelAndView.addObject("team",team);
//        return modelAndView;
//    }

}